### ISSUE TITLE
java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by JafferWilson** [OpenCCG/openccg#10]
I am trying to follow the steps from here: https://github.com/OpenCCG/openccg/blob/master/docs/ccgbank-README
Everyhting was quite fine but I am getting arithmetic error: Divide by Zero.
Kindly check the logs generated, which I have attached with the issue.

[log.ps.test.novel.txt](https://github.com/OpenCCG/openccg/files/1200817/log.ps.test.novel.txt)
[log.rz.test.novel.txt](https://github.com/OpenCCG/openccg/files/1200818/log.rz.test.novel.txt)

I hope to hear from you soon.

**Comment by mwhite14850** [comment]
If you look at the line that caused the exception, it's trying to compute a metric that has the number of sentences realized in the denominator.  If this number is zero, it means something has unfortunately gone wrong earlier in the process.  This can happen when the tool chain fails and then is re-run if the ant build thinks a step has succeeded when it really hasn't, leading to a crucial step getting mistakenly skipped.  (With ant/make, determining task success can sometimes be heuristic.)  The solution is usually to restart the process from scratch after resolving the original problem (eg a missing resource).

**Comment by JafferWilson** [comment]
Dear sir, I had figured it out that the process is trying to compute some sentence lenght divided by the another one. But what exactly might be the cause, is what I thought you might be helpful with. But I think what you have said, I need to restart the proces from scratch. Thank you for your advice and time. Glad by your help.
