### ISSUE TITLE
there are errors in openccg, how can i fixed them ??

### ISSUE THREAD

**Issue by gehadza** [OpenCCG/openccg#13]

**Comment by dmhowcroft** [comment]
Do you mean more generally, "what is the process for contributing to the project?", or specifically, "I have this problem and how do I fix it?"

**Comment by gehadza** [comment]
I mean the process for contributing to the project

**Comment by gehadza** [comment]
I want to run this project ,can you help me ??

**Comment by dmhowcroft** [comment]
What do you mean by 'run this project'?

**Comment by gehadza** [comment]
thanks :)
