### ISSUE TITLE
Issue during Installation

### ISSUE THREAD

**Issue by JustCunn** [OpenCCG/openccg#30]
Hi,

I've been trying to install OpenCCG from the Git Repo (as well as downloading the libraries needed from the other zip). When I come to building it with `ccg-build` I get this error:
```
./bin/ccg-build: Line 2: ./bin/ccg-build: ./ccg-env: not found
./bin/ccg-build: Line 18: ./bin/ccg-build: : Permission denied
```
Just to be clear, this is how `ccg-build` appears to me when I open it:
```
#!/bin/sh
. ccg-env
ANT_HOME="$OPENCCG_LIB"
PROPS="-Dant.home=$ANT_HOME -Dopenccg.home=$OPENCCG_HOME"
case `uname` in
  CYGWIN* ) XALAN_JARS="$OPENCCG_LIB/xalan.jar;$OPENCCG_LIB/xercesImpl.jar;$OPENCCG_LIB/xml-apis.jar;$OPENCCG_LIB/xsltc.jar;$OPENCCG_LIB/serializer.jar"
            ANT_JARS="$OPENCCG_LIB/ant.jar;$OPENCCG_LIB/ant-launcher.jar;$OPENCCG_LIB/ant-contrib.jar"
            ANT_JARS="$ANT_JARS;$OPENCCG_LIB/ant-junit.jar;$OPENCCG_LIB/ant-junit4.jar;$OPENCCG_LIB/junit-4.10.jar"
            CP="$JAVA_HOME/lib/tools.jar;$OPENCCG_JAR;$ANT_JARS;$XALAN_JARS;$DIRLIBS;."
            PROPS="$PROPS -Dcygwin=true"
  ;;
  * ) XALAN_JARS="$OPENCCG_LIB/xalan.jar:$OPENCCG_LIB/xercesImpl.jar:$OPENCCG_LIB/xml-apis.jar:$OPENCCG_LIB/xsltc.jar:$OPENCCG_LIB/serializer.jar"
      ANT_JARS="$OPENCCG_LIB/ant.jar:$OPENCCG_LIB/ant-launcher.jar:$OPENCCG_LIB/ant-contrib.jar"
      ANT_JARS="$ANT_JARS:$OPENCCG_LIB/ant-junit.jar:$OPENCCG_LIB/ant-junit4.jar:$OPENCCG_LIB/junit-4.10.jar"
      CP="$JAVA_HOME/lib/tools.jar:$OPENCCG_JAR:$ANT_JARS:$XALAN_JARS:$DIRLIBS:."
  ;;
esac
"$JAVA" $JAVA_MEM -classpath "$CP" $PROPS org.apache.tools.ant.launch.Launcher $@
```

I've set both environment variables, `JAVA_HOME` and `OPENCCG_HOME` but for some reason it just wont build. The file `ccg-env` also exists in the same folder as `ccg-build`.

Any help would be appreciated.

**Comment by mwhite14850** [comment]
Hi, sounds like you may not have added OPENCCG_HOME/bin to your PATH
environment variable?  -Mike

**Comment by JustCunn** [comment]
Hi. Yes that solved that problem. May I just ask, I'm now having a problem when it goes on to call `build.xml`. I now get this error message (although not all is an error statement):
```
Buildfile: /home/justin/openccg/build.xml

init:
     [echo] ----------- OpenCCG 0.9.5 [2013] ------------

prepare:

javacc:

compile:

compile-ccg2xml:

compile-ccg2xml.1:
     [echo] Compiling ccg2xml

compile-ccg2xml.default:
     [echo] (default compile)
     [exec] Traceback (most recent call last):
     [exec]   File "convert-ply.py", line 270, in <module>
     [exec]     print >> outfil, """#!/usr/bin/python
     [exec] TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean "print(<message>, file=<output_stream>)"?

BUILD FAILED
/home/justin/openccg/build.xml:141: The following error occurred while executing this line:
/home/justin/openccg/src/ccg2xml/build.xml:16: The following error occurred while executing this line:
/home/justin/openccg/src/ccg2xml/build.xml:39: The following error occurred while executing this line:
/home/justin/openccg/src/ccg2xml/build.xml:45: exec returned: 1

Total time: 1 second
```
I'm guessing this is a Python 3.X v. Python 2.X issue (I think). I've tried setting the `python` environment variable to launch Python2.7 but it did not help.

Sorry for the slight change in topic, but your help is appreciated.

**Comment by JustCunn** [comment]
I sorted this issue out. In case anyone is in a similar situation, changing the sha-bang (`#!`) in `convert-ply.py` to the specific python2.x directory did the trick. I also deactivated my Conda virtual environment but I don't think that was the answer.

**Comment by mwhite14850** [comment]
Cool, thanks for sharing.  Not sure that's been a common problem, but glad
you were able to find a workaround.

**Comment by AbeHandler** [comment]
I was able to resolve this by creating a python 2.7 environment and running the build in the environment. 

```
$ conda create -n myenv python=2.7
$ conda activate myenv 
$ ./bin/ccg-build
```
