### ISSUE TITLE
Build issue due to ant

### ISSUE THREAD

**Issue by jkallini** [OpenCCG/openccg#32]
Hello! I have been having a lot of trouble with installation due to an ant error when I run `./bin/ccg-build`:

```
Error: Could not find or load main class org.apache.tools.ant.launch.Launcher
Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.launch.Launcher
```

I'm using Mac OSX and I have ant version 1.10.9 installed. I tried updating my ANT_HOME variable, but that didn't seem to help. Do you have any suggestions about how to proceed?

**Comment by mwhite14850** [comment]
Have you set OPENCCG_HOME per the README?  If you look at ccg-build, it
puts the various ant jars on the java classpath.  To do so, it uses
OPENCCG_LIB, which is derived from OPENCCG_HOME in the ccg-env script.

**Comment by jkallini** [comment]
You're right - I just checked again and realized I changed my path, but didn't update `OPENCCG_HOME`. Thank you for the quick response, and sorry for the inconvenience.
