### ISSUE TITLE
Does the library generates paraphrases from the sentence itself or from a paraphrase DB? Please answer me as it is urgent.

### ISSUE THREAD

**Issue by JafferWilson** [OpenCCG/openccg#8]

**Comment by mwhite14850** [comment]
At present there is no off-the-shelf integration with an external paraphrase DB

**Comment by JafferWilson** [comment]
So does it generate the paraphrases itself? or I need to prepare paraphrase by myself and give it to the model for suggesting one. This will be hectic and not possible with my case. If your repository creates paraphrases on it own using the sentence, then it will be worth using the OpenCCG and I will cite in my project too.

**Comment by mwhite14850** [comment]
This [paper](http://aclweb.org/anthology/W16-1718) may help clarify what the library can do: it can generate some syntactic paraphrases on its own by chaining parsing and realization, while others require rewriting the semantic dependency graph that results from parsing; integrating lexical paraphrases could be done in a variety of ways in principle but there is no built-in way to do so.

**Comment by JafferWilson** [comment]
Thank you for your insights.
